# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# homebrew settings
eval "$(/opt/homebrew/bin/brew shellenv)"

# aliases
alias relogin='exec $SHELL -l'

# envs settings
if command -v anyenv > /dev/null; then
  eval "$(anyenv init -)"
fi

if command -v pyenv > /dev/null; then
  eval "$(pyenv init -)"
fi

if command -v exa > /dev/null; then
  alias ls='exa'
  alias la='ls -a'
  alias ll='ls -lbh'
  alias lt='ls -T'
  alias lla='ll -a'
  alias llt='ll -T'
  alias llta='ll -aT'
fi

if command -v bat > /dev/null; then
  alias cat='bat'
fi
